const SYNONYMS: Record<string, string> = {
  js: "javascript",
  ts: "typescript",
  reactjs: "react",
  "react.js": "react",
  vuejs: "vue",
  "vue.js": "vue",
  nodejs: "node.js",
  node: "node.js",
  k8s: "kubernetes",
  kube: "kubernetes",
  pg: "postgresql",
  postgres: "postgresql",
  mongo: "mongodb",
  tf: "terraform",
  py: "python",
  "c#": "csharp",
  dotnet: ".net",
  "asp.net": ".net",
  golang: "go",
  rb: "ruby",
  rails: "ruby on rails",
  "ruby-on-rails": "ruby on rails",
  aws: "amazon web services",
  gcp: "google cloud platform",
  "google cloud": "google cloud platform",
  azure: "microsoft azure",
  "microsoft azure": "microsoft azure",
  es6: "javascript",
  es2015: "javascript",
  jsx: "react",
  tsx: "typescript",
  sass: "scss",
  tailwindcss: "tailwind",
  graphql: "graphql",
  psql: "postgresql",
  mysql: "mysql",
  mssql: "sql server",
  "microsoft sql server": "sql server",
  redis: "redis",
  elastic: "elasticsearch",
  elk: "elasticsearch",
  kafka: "apache kafka",
  "apache kafka": "apache kafka",
  ci: "ci/cd",
  cd: "ci/cd",
  "github actions": "ci/cd",
  "gitlab ci": "ci/cd",
  jenkins: "ci/cd",
  docker: "docker",
  "docker compose": "docker",
  jest: "jest",
  vitest: "vitest",
  pytest: "pytest",
  unittest: "unit testing",
  rest: "rest api",
  "rest api": "rest api",
  restful: "rest api",
  grpc: "grpc",
};

export function canonicalizeSkill(raw: string): string {
  const lower = raw.toLowerCase().trim();
  return SYNONYMS[lower] ?? lower;
}

export function canonicalizeSkills(skills: string[]): string[] {
  return [...new Set(skills.map(canonicalizeSkill))];
}
